# Generated by Django 3.2.5 on 2021-08-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='browser',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
