# Generated by Django 3.2.5 on 2021-08-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usersession_browser'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='device_type',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
    ]
