# Generated by Django 3.2.5 on 2021-08-30 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usersession_device_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zip_code',
        ),
    ]
