# Generated by Django 3.2.5 on 2021-08-30 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_dislikecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likecomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='likecomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='DislikeComment',
        ),
        migrations.DeleteModel(
            name='LikeComment',
        ),
    ]
