# Generated by Django 3.2.5 on 2021-08-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_opinion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='n_dislikes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='n_likes',
        ),
        migrations.AlterField(
            model_name='opinion',
            name='action',
            field=models.IntegerField(choices=[(-1, 'dislike'), (0, 'neutral'), (1, 'like')], default=0),
        ),
    ]
