# Generated by Django 3.2.5 on 2021-08-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210830_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='n_views',
            field=models.IntegerField(default=0),
        ),
    ]
